# Generated by Django 5.2.8 on 2026-03-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='rate',
        ),
    ]
