# Generated by Django 5.2.8 on 2026-04-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_comment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
