# Generated by Django 5.2.8 on 2026-03-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_blocks_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
