# Generated by Django 5.2.8 on 2026-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_delete_basement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floors',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
