# Generated by Django 5.2.8 on 2026-03-30 04:25

import django.core.validators
import utils.compressor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_alter_floors_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='image',
            field=models.FileField(default=1, upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'heic', 'heif']), utils.compressor.check_image_size]),
            preserve_default=False,
        ),
    ]
